/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testfonster;

import java.beans.PropertyVetoException;

/**
 *
 * @author Anna Svensson
 */
public class TestFönster extends javax.swing.JFrame {

    FrmLoggaIn frmLoggaIn;
    FrmTest frmTest;
    /**
     * Creates new form TestFönster
     */
    public TestFönster() {
        initComponents();
        this.setSize(600, 400);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane2 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuLoggaIn = new javax.swing.JMenuItem();
        mnuAvsluta = new javax.swing.JMenuItem();
        frmEditMeny = new javax.swing.JMenu();
        frmTestMeny = new javax.swing.JMenu();
        mnuTest1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane2Layout = new javax.swing.GroupLayout(jDesktopPane2);
        jDesktopPane2.setLayout(jDesktopPane2Layout);
        jDesktopPane2Layout.setHorizontalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        jDesktopPane2Layout.setVerticalGroup(
            jDesktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Meny");

        mnuLoggaIn.setText("Logga in");
        mnuLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLoggaInActionPerformed(evt);
            }
        });
        jMenu1.add(mnuLoggaIn);

        mnuAvsluta.setText("Avsluta");
        jMenu1.add(mnuAvsluta);

        jMenuBar1.add(jMenu1);

        frmEditMeny.setText("Edit");
        jMenuBar1.add(frmEditMeny);

        frmTestMeny.setText("Test");

        mnuTest1.setText("Test1");
        mnuTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuTest1ActionPerformed(evt);
            }
        });
        frmTestMeny.add(mnuTest1);

        jMenuBar1.add(frmTestMeny);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLoggaInActionPerformed
        //Inloggningsfönstret
        if(frmLoggaIn == null || frmLoggaIn.isClosed()) {
        frmLoggaIn = new FrmLoggaIn();
        jDesktopPane2.add(frmLoggaIn);
        frmLoggaIn.setLocation(this.getWidth()/2 - frmLoggaIn.getWidth()/2, this.getHeight()/2 - frmLoggaIn.getHeight()/2);
        frmLoggaIn.setVisible(true);
        }
        else
        {
        frmLoggaIn.setLocation(this.getWidth()/2 - frmLoggaIn.getWidth()/2, this.getHeight()/2 - frmLoggaIn.getHeight()/2);
        frmLoggaIn.setVisible(true); 
        }
        
    }//GEN-LAST:event_mnuLoggaInActionPerformed

    private void mnuTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuTest1ActionPerformed
        //Det stora fönstret
        if(frmTest == null || frmTest.isClosed()) {
        frmTest = new FrmTest();
        jDesktopPane2.add(frmTest);
        frmTest.setVisible(true);
        }
        else
        {
        frmTest.setVisible(true);
        }

        try { 
            frmTest.setMaximum(true);
        }catch (PropertyVetoException ettUndantag) {
            
        }
        
            frmTest.setBorder(null);
            ((javax.swing.plaf.basic.BasicInternalFrameUI)
            frmTest.getUI()).setNorthPane(null); 
    }//GEN-LAST:event_mnuTest1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFönster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFönster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFönster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFönster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFönster().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu frmEditMeny;
    private javax.swing.JMenu frmTestMeny;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAvsluta;
    private javax.swing.JMenuItem mnuLoggaIn;
    private javax.swing.JMenuItem mnuTest1;
    // End of variables declaration//GEN-END:variables
}

