/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwartsit;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ellin
 */
public class FrmAdminGeLarareAdminStatus extends javax.swing.JInternalFrame {
    
     private static InfDB idb;

    /**
     * Creates new form FrmAdminGeLarareAdminStatus
     */
    public FrmAdminGeLarareAdminStatus(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        tfSokLarare = new javax.swing.JTextField();
        btnSpara = new javax.swing.JButton();

        jLabel1.setText("Sök lärare att ge administratörstatus:");

        tfSokLarare.setColumns(15);

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tfSokLarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnSpara))
                    .addComponent(jLabel1))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfSokLarare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSpara))
                .addContainerGap(349, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        try {
            //Kontrollerar att textfältet inte är tomt.
            if (Validering.textfaltHarVarde(tfSokLarare)) {
                // Hämtar texten i textfältet SokLarare, splittar strängen vid mellanslag och skapar en array av strängar.
                String[] lararNamnet = tfSokLarare.getText().trim().split("\\s+");
                String forNamn = lararNamnet[0];
                String efterNamn = lararNamnet[1];
                //Hämtar info om läraren har Administratörsstatus eller inte
                String adminStatus = idb.fetchSingle("SELECT Administrator FROM Larare WHERE Fornamn = \'" + forNamn + "\' AND efternamn = \'" + efterNamn + "\'");
                // Om administratörsstatus är F så ska man ändra den till T
                if (adminStatus.equals("F")) {
                    idb.update("UPDATE Larare SET Administrator = 'T' WHERE Fornamn = \'" + forNamn + "\' AND efternamn = \'" + efterNamn + "\'");
                    JOptionPane.showMessageDialog(null, forNamn + " " + efterNamn + " har fått administratörsstatus.");

                }
                // Om administratörsstatus är T så ska felmeddelande skrivas ut om att läraren redan har administratörsstatus
                if (adminStatus.equals("T")) {
                    JOptionPane.showMessageDialog(null, forNamn + " " + efterNamn + " har redan administratörsstatus.");
                }
            }
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel");
        }

    }//GEN-LAST:event_btnSparaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSpara;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField tfSokLarare;
    // End of variables declaration//GEN-END:variables
}
