/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hogwartsit;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
/**
 *
 * @author Anna Svensson och Ellinor Danielsson
 */
public class FrmElevElevhemsPokal extends javax.swing.JInternalFrame {

    private static InfDB idb;
    
    /**
     * Creates new form FrmElevElevhemsPokal
     */
    public FrmElevElevhemsPokal(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeStallning = new javax.swing.JLabel();
        spAktuellStallning = new javax.swing.JScrollPane();
        taAktuellStallning = new javax.swing.JTextArea();
        btnSok = new javax.swing.JButton();

        lblSeStallning.setText("Se aktuell ställning i elevhemspokalen:");

        taAktuellStallning.setEditable(false);
        taAktuellStallning.setColumns(20);
        taAktuellStallning.setRows(5);
        spAktuellStallning.setViewportView(taAktuellStallning);

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(spAktuellStallning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSeStallning)
                    .addComponent(btnSok))
                .addGap(135, 135, 135))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblSeStallning)
                .addGap(18, 18, 18)
                .addComponent(spAktuellStallning, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSok)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        //Lokal variabel för att visa aktuell position för elevhemmet.
        int stallning = 0;
        //Tömmer textrutan från eventuell tidigare text
        taAktuellStallning.setText("");
        
        try {
            //Hämtar elevhemsnamn och huspoäng, och sorterar elevhemmen i fallande ordning efter antal huspoäng.
            ArrayList<HashMap<String, String>> resultat = idb.fetchRows("SELECT elevhemsnamn, huspoang FROM Elevhem \n" +
                    "ORDER BY huspoang DESC");
            //Loopar igenom ArrayListen och hämtar elevhemsnamn och huspoäng för varje elevhem i ArrayListens HashMap
            for (int i = 0; i < resultat.size(); i++) {
                String elevhemsNamn = resultat.get(i).get("ELEVHEMSNAMN");
                String husPoang = resultat.get(i).get("HUSPOANG");
                //För varje iteration ökar värdet på variablen stallningen med 1.
                stallning ++;
                //Lägger till ställning, elevhemsnamn och huspoäng i textrutan.
                taAktuellStallning.append(stallning + ". " + elevhemsNamn + ", " + husPoang + " poäng.\n");
            }
        }
        
        catch (InfException ettUndantag) {
            ettUndantag.getMessage();
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnSokActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JLabel lblSeStallning;
    private javax.swing.JScrollPane spAktuellStallning;
    private javax.swing.JTextArea taAktuellStallning;
    // End of variables declaration//GEN-END:variables
}
